name: CI Study

on:
  push:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses : actions/checkout@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: First Step
        npm install
        npm test
        npm build
